# Generated by Django 5.0.6 on 2024-07-17 11:57
import json

from django.db import migrations, transaction

from shoe.models import Category


def populate_categories(apps, schema_editor):
    # Load JSON data
    with open('media/json/db_populate_data.json', 'r') as file:
        data = json.load(file)

        # Load categories
        categories = data.get('categories', [])

        category_list = [
            Category(id=category['id'], name=category['name'])
            for category in categories
        ]

        with transaction.atomic():
            Category.objects.bulk_create(category_list)


class Migration(migrations.Migration):
    dependencies = [
        ('shoe', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_categories),
    ]
