# Generated by Django 5.0.6 on 2024-07-17 12:00
import json

from django.db import migrations, transaction

from shoe.models import Shoe, ShoeSize


def populate_shoes_and_sizes(apps, schema_editor):
    # Load JSON data
    with open('media/json/db_populate_data.json', 'r') as file:
        data = json.load(file)

        # Load categories
        shoes = data.get('shoes', [])
        shoe_list = []
        shoes_sizes = []

        for shoe in shoes:
            shoe_object = Shoe(
                id=shoe['id'],
                name=shoe['name'],
                image_url=shoe['image_url'],
                price=shoe['price'],
                description=shoe['description'],
                category_id=shoe['category_id']
            )

            shoe_size_list = [
                ShoeSize(
                    shoe=shoe_object,
                    size=size
                )
                for size in shoe['sizes']
            ]

            shoes_sizes.extend(shoe_size_list)
            shoe_list.append(shoe_object)

        with transaction.atomic():
            Shoe.objects.bulk_create(shoe_list)
            ShoeSize.objects.bulk_create(shoes_sizes)


class Migration(migrations.Migration):
    dependencies = [
        ('shoe', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_shoes_and_sizes),
    ]
