# Generated by Django 5.0.6 on 2024-07-17 11:57
import json

from django.db import migrations, transaction

from shoe.models import Collection


def populate_collections(apps, schema_editor):
    # Load JSON data
    with open('media/json/db_populate_data.json', 'r') as file:
        data = json.load(file)

        # Load categories
        collections = data.get('collections', [])

        collection_list = [
            Collection(id=collection['id'], name=collection['name'])
            for collection in collections
        ]

        with transaction.atomic():
            Collection.objects.bulk_create(collection_list)


class Migration(migrations.Migration):
    dependencies = [
        ('shoe', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_collections),
    ]
