# Generated by Django 5.0.6 on 2024-07-17 12:00
import json
import random

from django.db import migrations, transaction

from shoe.models import Product, ProductVariant


def populate_shoes_and_sizes(apps, schema_editor):
    # Load JSON data
    with open('media/json/db_populate_data.json', 'r') as file:
        data = json.load(file)

        # Load categories
        shoes = data.get('shoes', [])
        shoe_list = []
        shoes_variants = []

        for shoe in shoes:
            shoe_object = Product(
                id=shoe['id'],
                name=shoe['name'],
                image_url=shoe['image_url'],
                price=shoe['price'],
                description=shoe['description'],
                collection_id=shoe['collection_id']
            )

            shoe_variant_list = [
                ProductVariant(
                    product=shoe_object,
                    variant=variant['variant'],
                    stock=random.randint(10, 50)
                )
                for variant in shoe['variants']
            ]

            shoes_variants.extend(shoe_variant_list)
            shoe_list.append(shoe_object)

        with transaction.atomic():
            Product.objects.bulk_create(shoe_list)
            ProductVariant.objects.bulk_create(shoes_variants)


class Migration(migrations.Migration):
    dependencies = [
        ('shoe', '0001_initial'),
        ('shoe', '0002_populate_collection'),
    ]

    operations = [
        migrations.RunPython(populate_shoes_and_sizes),
    ]
