# Generated by Django 5.0.6 on 2024-07-18 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoe', '0002_populate_shoes'),
        ('user', '0002_create_super_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='shoe_size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shoe.shoesize'),
        ),
    ]
