# Generated by Django 5.0.6 on 2024-07-17 11:57
import os
import json
from django.conf import settings
from django.db import migrations, transaction
from product.models import Collection

def populate_collections(apps, schema_editor):
    # Load JSON data
    with open(os.path.join(settings.SEEDER_DIR, 'collections.json'), 'r') as file:
        collections = json.load(file)

        collection_list = [
            Collection(id=collection['id'], name=collection['name'])
            for collection in collections
        ]

        with transaction.atomic():
            Collection.objects.bulk_create(collection_list)


class Migration(migrations.Migration):
    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_collections),
    ]
