# Generated by Django 5.0.6 on 2024-07-17 12:00
import os
import json
import random
from django.conf import settings
from django.db import migrations, transaction
from product.models import Product, ProductVariant

def populate_products_and_variants(apps, schema_editor):
    # Load JSON data
    with open(os.path.join(settings.SEEDER_DIR, 'products.json'), 'r') as file:
        products = json.load(file)

        # Load categories
        product_list = []
        product_variants = []

        for product in products:
            product_object = Product(
                id=product['id'],
                name=product['name'],
                image_url=product['image_url'],
                price=product['price'],
                description=product['description'],
                collection_id=product['collection_id']
            )

            products_variant_list = [
                ProductVariant(
                    product=product_object,
                    variant=variant['variant'],
                    stock=random.randint(10, 50)
                )
                for variant in product['variants']
            ]

            product_list.append(product_object)
            product_variants.extend(products_variant_list)

        with transaction.atomic():
            Product.objects.bulk_create(product_list)
            ProductVariant.objects.bulk_create(product_variants)


class Migration(migrations.Migration):
    dependencies = [
        ('product', '0001_initial'),
        ('product', '0002_populate_collection'),
    ]

    operations = [
        migrations.RunPython(populate_products_and_variants),
    ]
